'use strict';
const {poems,categories}=__POETRY_DATA__;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let reduced=store.get('poetry-motion')==='reduced'||matchMedia('(prefers-reduced-motion: reduce)').matches;
let theme=store.get('poetry-theme')||'light',paused=false,view={kind:'home'},selected=null,user=null,registering=false,showPinyin=false,explanation=null;
let nodes=[],yaw=.2,pitch=-.12,pointer={x:0,y:0},hover=false,drag=null,last=0,frame=0,wheelVelocity=0;
const sphere=$('#sphere');
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e}
function notify(text){$('#notice').textContent=text;$('#notice').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').classList.remove('show'),3200)}
function applyTheme(value){theme=value;document.documentElement.dataset.theme=value;store.set('poetry-theme',value);$$('[data-theme-value]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.themeValue===value));drawSky()}
function applyMotion(){document.documentElement.dataset.motion=reduced?'reduced':'normal';$('#reduce-motion').checked=reduced;store.set('poetry-motion',reduced?'reduced':'normal');updatePause()}
function updatePause(){$('#pause').textContent=paused||reduced?'开始转动':'暂停转动';$('#pause').setAttribute('aria-label',paused||reduced?'开始球体旋转':'暂停球体旋转')}
function drawSky(){const c=$('#sky'),d=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.scale(d,d);let seed=73;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};for(let i=0;i<Math.min(220,w*h/5500);i++){const x=rand()*w,y=rand()*h,r=rand()*.9+.2;ctx.fillStyle=`rgba(209,223,255,${rand()*.45+.12})`;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
function matches(p,label){return p.dynasty===label||p.author===label||p.tags.includes(label)}
const authors=[...new Set(poems.map(p=>p.author))].filter(a=>a!=='佚名');
function makeNodes(items){sphere.replaceChildren();nodes=items.map((item,i)=>{const y=1-2*(i+.5)/items.length,r=Math.sqrt(1-y*y),theta=i*Math.PI*(3-Math.sqrt(5));const button=element('button',item.label,'node');button.type='button';button.setAttribute('aria-label',item.kind==='poem'?`阅读《${item.label}》`:`浏览${item.label}分类`);button.addEventListener('click',()=>{if(performance.now()<(sphere.blockClickUntil||0))return;item.kind==='poem'?openPoem(item.id):openCategory(item.label)});button.addEventListener('focus',()=>{if(button.matches(':focus-visible'))hover=true});button.addEventListener('blur',()=>hover=false);sphere.append(button);return {x:Math.cos(theta)*r,y,z:Math.sin(theta)*r,button,item}});yaw=.2;pitch=-.12;project()}
function project(){if(view.kind==='poem')return;const w=sphere.clientWidth,h=sphere.clientHeight,radius=Math.min(w*.39,h*.43,330),cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch);for(const n of nodes){const x=n.x*cy+n.z*sy,z0=n.z*cy-n.x*sy,y=n.y*cx-z0*sx,z=n.y*sx+z0*cx;const perspective=2.8/(2.8-z*.42),depth=(z+1)/2;n.button.style.transform=`translate(-50%,-50%) translate(${x*radius*perspective}px,${y*radius*perspective}px) scale(${.66+depth*.4})`;n.button.style.opacity=String(.25+depth*.75);n.button.style.zIndex=String(Math.round(depth*100));}}
function loop(t){const dt=Math.min((t-last)/1000,.04)||.016;last=t;if(!document.hidden&&view.kind!=='poem'&&!$('#app').hidden){if(!paused&&!reduced&&!drag&&(!hover||Math.abs(wheelVelocity)>.02)&&!document.querySelector('dialog[open]')){yaw+=dt*(.075+wheelVelocity);pitch=Math.max(-.7,Math.min(.7,pitch+dt*pointer.y*.12))}wheelVelocity*=Math.exp(-2*dt);if(Math.abs(wheelVelocity)<.001)wheelVelocity=0;project()}frame=requestAnimationFrame(loop)}
// Normalize wheel / trackpad units, reverse immediately, and ease back to auto rotation.
$('#universe').addEventListener('wheel',e=>{
  if(e.ctrlKey||e.metaKey||$('#app').hidden||document.querySelector('dialog[open]'))return;
  const raw=Math.abs(e.deltaY)>=Math.abs(e.deltaX)?e.deltaY:e.deltaX;
  if(!raw)return;
  e.preventDefault();
  const unit=e.deltaMode===1?16:e.deltaMode===2?sphere.clientHeight:1;
  const delta=Math.max(-160,Math.min(160,raw*unit));
  if(paused||reduced){yaw+=delta*.002;wheelVelocity=0;project();return}
  if(Math.sign(delta)!==Math.sign(wheelVelocity))wheelVelocity=0;
  wheelVelocity=Math.max(-2.4,Math.min(2.4,wheelVelocity+delta*.007));
},{passive:false});
sphere.addEventListener('pointermove',e=>{const b=sphere.getBoundingClientRect();pointer.x=(e.clientX-b.left)/b.width*2-1;pointer.y=(e.clientY-b.top)/b.height*2-1;if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.distance+=Math.abs(dx)+Math.abs(dy);yaw+=dx*.006;pitch=Math.max(-1.2,Math.min(1.2,pitch-dy*.006));drag.x=e.clientX;drag.y=e.clientY;project()}else hover=!!e.target.closest('.node')});
sphere.addEventListener('pointerleave',()=>{pointer={x:0,y:0};hover=false});sphere.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;drag={x:e.clientX,y:e.clientY,distance:0}});window.addEventListener('pointerup',()=>{if(drag?.distance>8)sphere.blockClickUntil=performance.now()+250;drag=null});window.addEventListener('pointercancel',()=>drag=null);
function updateRoute(hash){if(location.hash!==hash)history.pushState(null,'',hash)}
function openHome(push=true){view={kind:'home'};selected=null;$('#reading').hidden=true;$('#universe').hidden=false;$('#back').hidden=true;$('#context').hidden=true;$('#context').replaceChildren();$('#sphere-caption').hidden=true;$('#sphere-caption').textContent='';makeNodes([...categories,...authors].map(label=>({label,kind:'category'})));if(push)updateRoute('#');window.scrollTo(0,0)}
function openCategory(label,push=true){if(![...categories,...authors].includes(label))return;view={kind:'category',label};selected=null;$('#reading').hidden=true;$('#universe').hidden=false;$('#back').hidden=false;const list=poems.filter(p=>matches(p,label));$('#context').hidden=false;$('#context').replaceChildren(element('h1',label));$('#sphere-caption').hidden=true;$('#sphere-caption').textContent='';makeNodes(list.map(p=>({label:p.title,kind:'poem',id:p.id})));if(push)updateRoute('#category/'+encodeURIComponent(label));window.scrollTo(0,0)}
function openPoem(id,push=true){const p=poems.find(p=>p.id===id);if(!p)return;if(view.kind==='category')openPoem.from=view.label;selected=p;view={kind:'poem',id};showPinyin=false;explanation=null;$('#universe').hidden=true;$('#reading').hidden=false;$('#back').hidden=false;$('#poem-title').textContent=p.title;$('#poem-source').textContent=`${p.dynasty} · ${p.author}`;renderPoem();renderExplanation();if(push)updateRoute('#poem/'+p.id);window.scrollTo(0,0)}
function renderPoem(){const target=$('#poem-lines');target.replaceChildren();target.classList.toggle('has-pinyin',showPinyin);selected.lines.forEach((line,i)=>{const row=element('p');if(!showPinyin)row.textContent=line;else{[...line].forEach((ch,j)=>{const sound=selected.pinyin[i][j];if(!/[\u3400-\u9fff]/.test(ch)){row.append(document.createTextNode(ch));return}const ruby=element('ruby',ch);ruby.append(element('rt',sound));row.append(ruby)})}target.append(row)});$('#phonetic').setAttribute('aria-pressed',showPinyin)}
function renderExplanation(){$('#explanation').hidden=!explanation;$('#translate').setAttribute('aria-pressed',explanation==='translation');$('#appreciate').setAttribute('aria-pressed',explanation==='analysis');if(explanation){$('#explanation-title').textContent=explanation==='translation'?'译文':'赏析';$('#explanation-text').textContent=selected[explanation]}}
function route(){const [kind,value]=location.hash.slice(1).split('/');if(kind==='category'){try{openCategory(decodeURIComponent(value),false)}catch{openHome(false)}}else if(kind==='poem'&&poems.some(p=>p.id===value))openPoem(value,false);else openHome(false)}
$('#back').addEventListener('click',()=>view.kind==='poem'&&openPoem.from?openCategory(openPoem.from):openHome());window.addEventListener('popstate',route);
$('#pause').addEventListener('click',()=>{if(reduced){reduced=false;paused=false;applyMotion()}else paused=!paused;updatePause()});
$('#translate').addEventListener('click',()=>{explanation=explanation==='translation'?null:'translation';renderExplanation();if(explanation)$('#explanation').scrollIntoView({behavior:reduced?'instant':'smooth',block:'nearest'})});$('#appreciate').addEventListener('click',()=>{explanation=explanation==='analysis'?null:'analysis';renderExplanation();if(explanation)$('#explanation').scrollIntoView({behavior:reduced?'instant':'smooth',block:'nearest'})});$('#phonetic').addEventListener('click',()=>{showPinyin=!showPinyin;renderPoem()});
function modal(id){$('#menu').hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false');$(id).showModal()}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$('#menu-toggle').addEventListener('click',()=>{$('#menu').hidden=!$('#menu').hidden;$('#menu-toggle').setAttribute('aria-expanded',!$('#menu').hidden)});document.addEventListener('click',e=>{if(!e.target.closest('.account')){$('#menu').hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#menu').hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false')}});
$('#settings-open').addEventListener('click',()=>modal('#settings-dialog'));$$('[data-theme-value]').forEach(b=>b.addEventListener('click',()=>applyTheme(b.dataset.themeValue)));$('#reduce-motion').addEventListener('change',e=>{reduced=e.target.checked;applyMotion()});
function normalize(q){return q.toLowerCase().replace(/[\s，。！？、·《》：；,.!?]/g,'')}
function fuzzy(needle,haystack){let i=0;for(const c of haystack){if(c===needle[i])i++;if(i===needle.length)return true}return false}
function search(q){const n=normalize(q);if(!n)return [];return poems.map(p=>{const title=normalize(p.title),author=normalize(p.author),content=normalize(p.lines.join('')),tags=normalize(p.dynasty+p.tags.join(''));let score=title===n?100:author===n?90:title.includes(n)?80:author.includes(n)?75:content.includes(n)?70:tags.includes(n)?60:fuzzy(n,title)||fuzzy(n,content)?30:0;return {p,score}}).filter(x=>x.score).sort((a,b)=>b.score-a.score).map(x=>x.p)}
function renderSearch(){const q=$('#search-input').value.trim(),root=$('#search-results');root.replaceChildren();if(!q){root.append(element('p','试试「明月」「李白」或「思乡」','empty'));return}const matches=search(q);if(!matches.length){root.append(element('p','尚未找到这句诗。试试更短的词，或其他作者与意象。','empty'));return}for(const p of matches){const b=element('button',undefined,'search-result');b.append(element('strong',p.title),element('small',`${p.dynasty} · ${p.author}`),element('p',p.lines[0]));b.addEventListener('click',()=>{$('#search-dialog').close();openPoem.from=null;openPoem(p.id)});root.append(b)}}
$('#search-toggle').addEventListener('click',()=>{modal('#search-dialog');renderSearch();$('#search-input').focus()});$('#search-input').addEventListener('input',renderSearch);
async function api(path,body){const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin'});let data;try{data=await response.json()}catch{throw Error('服务暂时不可用，请稍后重试。')}if(!response.ok)throw Error(data.error||'请求失败，请稍后重试。');return data}
function renderUser(){$('#logout').hidden=!user;$('#account-email').hidden=!user;$('#account-email').textContent=user?.email||'';$('#avatar').setAttribute('aria-label',user?'查看账号 '+user.email:'登录或注册');$('#avatar').title=user?.email||'登录或注册';if(user)$('#avatar').textContent=user.email[0].toUpperCase();else $('#avatar').innerHTML='<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/></svg>'}
function authMode(){registering=!registering;$('#auth-title').textContent=registering?'初见片刻':'回到片刻';$('#auth-subtitle').textContent=registering?'注册后将自动登录，进入诗词星河。':'以邮箱登录，继续与诗相逢。';$('#auth-submit').textContent=registering?'注册并登录':'登录';$('#auth-switch').textContent=registering?'已有账号？登录':'还没有账号？注册';$('#agreement-row').hidden=!registering;$('#agree').required=registering;$('#password').autocomplete=registering?'new-password':'current-password';$('#auth-error').textContent=''}
$('#avatar').addEventListener('click',()=>{if(user){$('#menu').hidden=false;$('#menu-toggle').setAttribute('aria-expanded','true')}else modal('#auth-dialog')});$('#auth-switch').addEventListener('click',authMode);$('#terms-open').addEventListener('click',()=>modal('#terms-dialog'));
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('#auth-submit');button.disabled=true;$('#auth-switch').disabled=true;$('#auth-error').textContent='';try{const data=await api(registering?'register':'login',{email:$('#email').value.trim(),password:$('#password').value,agreement:$('#agree').checked});user=data.user;renderUser();$('#auth-dialog').close();$('#password').value='';openHome();notify(registering?'注册成功，欢迎来到片刻。':'已登录，欢迎回来。')}catch(e){$('#auth-error').textContent=e.message}finally{button.disabled=false;$('#auth-switch').disabled=false}});
$('#logout').addEventListener('click',async()=>{try{await api('logout',{});user=null;renderUser();$('#menu').hidden=true;notify('已退出登录。')}catch(e){notify(e.message)}});
async function refreshUser(){try{user=(await api('me')).user;renderUser()}catch{notify('账号服务暂时不可用，仍可浏览诗词。')}}
function finishIntro(){$('#app').hidden=false;$('#intro').classList.add('exit');project();setTimeout(()=>$('#intro').hidden=true,reduced?0:1100)}
function intro(){const candidates=poems.filter(p=>p.lines[0].length<=16);const p=candidates[Math.floor(Math.random()*candidates.length)],h=element('h1',undefined,'intro-poem');p.lines[0].match(/[^，。！？]+[，。！？]?/g).forEach((s,i)=>{const span=element('span',s);span.style.animationDelay=i*.2+'s';h.append(span)});$('#intro-content').append(h,element('p',`${p.dynasty} · ${p.author}　《${p.title}》`,'intro-source'));setTimeout(finishIntro,reduced?1700:3200)}
window.addEventListener('resize',()=>{drawSky();project()});applyTheme(theme);applyMotion();route();intro();refreshUser();requestAnimationFrame(loop);
if(document.modelContext?.registerTool){for(const tool of [{name:'search_poems',description:'Search the poetry collection by title, author, verse or category.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:({query})=>{if(typeof query!=='string'||!query.trim())throw Error('需要搜索词');return search(query).map(p=>({id:p.id,title:p.title,author:p.author}))}},{name:'open_poem',description:'Open a poem in the reading view.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},execute:({id})=>{if(!poems.some(p=>p.id===id))throw Error('未找到诗词');finishIntro();openPoem(id);return {id,title:selected.title}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
